version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: intranet_prueba_db
      MYSQL_ROOT_PASSWORD: password123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
      - ./backend/staticfiles:/app/staticfiles  # Añadido para archivos estáticos
    ports:
      - "8001:8001"
    depends_on:
      - db
  frontend:
    build: ./frontend
    command: npm run dev -- --host --port 3000
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  db_data: