# Generated by Django 4.2.20 on 2025-03-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vacationrequest_shiftchangerequest_permissionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionrequest',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='start_date',
            field=models.DateField(),
        ),
    ]
