# Generated by Django 4.2.20 on 2025-03-17 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_permissionrequest_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('sales_target', models.FloatField(default=0)),
                ('sales_achieved', models.FloatField(default=0)),
                ('warranties_target', models.FloatField(default=0)),
                ('warranties_achieved', models.FloatField(default=0)),
                ('financing_target', models.FloatField(default=0)),
                ('financing_achieved', models.FloatField(default=0)),
                ('reviews_target', models.FloatField(default=0)),
                ('reviews_achieved', models.FloatField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpis', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
