# Generated by Django 4.2.20 on 2025-03-18 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_kpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kpis_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kpi',
            name='period',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='reviews_achieved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='reviews_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='warranties_achieved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='warranties_target',
            field=models.IntegerField(default=0),
        ),
    ]
