# Generated by Django 4.2.20 on 2025-03-19 08:14

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='news_read', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
