# Generated by Django 4.2.20 on 2025-03-20 23:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_task_description_remove_task_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kpi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='news',
            name='department',
            field=models.CharField(choices=[('all', 'Todos'), ('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3')], default='all', max_length=3),
        ),
        migrations.AddField(
            model_name='promotion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='kpi',
            unique_together={('worker', 'period')},
        ),
    ]
