# Generated by Django 4.2.20 on 2025-03-22 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_kpi_created_at_kpi_updated_at_news_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionrequest',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shiftchangerequest',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shiftchangerequest',
            name='reason',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shiftchangerequest',
            name='acceptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_acceptances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shiftchangerequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='period',
            field=models.CharField(max_length=20),
        ),
    ]
