# Generated by Django 4.2.20 on 2025-03-22 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_permissionrequest_hidden_shiftchangerequest_hidden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionrequest',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='shiftchangerequest',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='vacationrequest',
            name='hidden',
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='hidden_by',
            field=models.ManyToManyField(blank=True, related_name='hidden_permission_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftchangerequest',
            name='hidden_by',
            field=models.ManyToManyField(blank=True, related_name='hidden_shift_change_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='hidden_by',
            field=models.ManyToManyField(blank=True, related_name='hidden_vacation_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
