# Generated by Django 4.2.20 on 2025-03-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_permissionrequest_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_reset_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
